# Generated by Django 2.2.16 on 2022-11-27 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20221127_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='autor',
            new_name='author',
        ),
    ]
